#!/bin/bash
if [ -f /etc/rc.local ]
then
    cat /etc/rc.local | grep -v "exit 0" | grep -v "chonos-nettest" > /tmp/rc.local
    echo "exit 0" >> /tmp/rc.local
    cat /tmp/rc.local > /etc/rc.local
fi